// vue-app/src/App.vue
<template>
  <div>
    <h1>Making decisions based on the weather forecast</h1>
    <h3>Next daytime temperature: {{ firstDaytimePeriod.temperature }}</h3>
    <BikeRecommender :recommendation="bikeRecommendation" />
    <UmbrellaRecommender :recommendation="umbrellaRecommendation" />
    <BarChart :data="periods" :height="400" :width="600" />
  </div>
</template>

<script>
import BikeRecommender from "./components/BikeRecommender.vue";
import UmbrellaRecommender from "./components/UmbrellaRecommender.vue";
import BarChart from "./components/BarChart.vue";

const API_URL = "https://api.weather.gov/gridpoints/OKX/33,37/forecast";

export default {
  name: "App",
  components: {
    BikeRecommender,
    UmbrellaRecommender,
    BarChart,
  },
  data() {
    return {
      forecast: null,
    };
  },
  computed: {
    firstDaytimePeriod() {
      if (!this.forecast) {
        return {};
      }
      console.log(this.forecast);
      const daytimePeriod = this.forecast.properties.periods.find(
        (d) => d.isDaytime
      );
      return daytimePeriod || {};
    },
    recommendation() {
    periods() {
      if (!this.forecast || !this.forecast.properties) {
        return [];
      }
      return this.forecast.properties.periods;
    },
    firstDaytimePeriod() {
      const daytimePeriod = this.periods.find((d) => d.isDaytime);
      return daytimePeriod || {};
    },
    bikeRecommendation() {
      const { temperature } = this.firstDaytimePeriod;
      if (temperature === undefined) {
        return null;
      }
      return temperature >= 45 && temperature < 80;
    },
    umbrellaRecommendation() {
      if (!this.periods.length) {
        return false;
      }
      const nextDaytimeForecast = this.forecast.properties.periods.find(
        (d) => d.isDaytime
      );
      if (!nextDaytimeForecast) {
        return false;
      }
      return nextDaytimeForecast.shortForecast.includes("Rain");
    },
  },
  mounted() {
    fetch(API_URL)
      .then((res) => res.json())
      .then((data) => {
        this.forecast = data;
      });
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// svelte-app/src/App.svelte
<script>
	import { onMount } from 'svelte';
	import BarChart from './BarChart.svelte'
	import Forecast from './Forecast.svelte'

	const API_URL = "https://api.weather.gov/gridpoints/OKX/33,37/forecast";

	let forecast = {
		properties: {
			periods: []
		}
	};

	onMount(async () => {
		const res = await fetch(API_URL);
		forecast = await res.json();
	});
</script>

<main>
	<h4>This week's temperature chart</h4>
	<Forecast periods={forecast.properties.periods} />
	<BarChart data={forecast.properties.periods} height={400} width={600} />
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>
